version: "3"
services:
  status:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - public
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  dns:
    image: ntweb-dns
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - platform
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  git:
    image: gogs/gogs
    ports:
      - "22:22"
    volumes:
      - /media/ntrrg/NtServer/Server/services/gogs:/data
    networks:
      - public
    deploy:
      restart_policy:
        condition: on-failure
  web:
    depends_on:
      - git
      - status
    image: ntweb-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /media/ntrrg/NtServer/Work/NtWeb/Certs:/etc/letsencrypt:ro
      - /media/ntrrg/NtServer/Work/NtWeb/Repositories/ntrrg.github.io:/srv/web:ro
      - /media/ntrrg/NtServer/Software/Linux/Mirrors:/srv/mirrors:ro
    networks:
      - public
    deploy:
      replicas: 1
networks:
  platform:
  public:
